cd/
mkdir rede
cd rede
mkdir ALAN-SOARES ANDREA-SANTOS BRUNO-OLIVEIRA CAMILA-LIRA CARLOS-SOUSA DANIEL-SANTANA DARIO-FARIAS EDUARDO-RIOS FAVIO-SILVA FELIPE-MACHADO FELIPE-BARRIOS FLAVIO-SOUZA FRANCISCO-CAVALCANTE GABRIEL-CREPALDI GABRIEL-LIMA GABRIEL-RODRIGUES GABRIELY-SILVA GUILHERME-ALVES GUSTAVO-TAVARES HENRIQUE-CABRAL ISAAC-SOUZA ISABELLY-MESQUITA JOAO-SOARES
dir
cls
mkdir JONATHAN-FREITAS KAUA-MOTA LUCAS-SANTOS LUCAS-ANDRADE MATHEUS-CARVALHO NATALIA-MOREIRA NICOLAS-NASCIMENTO PALLOMA-SANTOS RAISSA-CARMO RAPHAELA-MELO REBECCA-GUEDES RIAM-ANDRE ROGERIO-JUNIOR SABRINA-BENEVIDES WALDANIA-OLIVEIRA
dir
cls